### ISSUE TITLE
CSS/JS/Partial

### ISSUE THREAD

**Issue by csainty** [Code52/aspnet-internationalization#11]
Firstly, .ascx? Ew :)
Had to rename to .cshtml and strip the declaration at the top.
I remove the webform renderer from my pipeline to speed it up.
Not sure what the best approach there is.
Perhaps include all common versions?

The CSS file seems to have a whole section referencing HTML elements that don't exist.
eg #langauge { }

The partial has some doubled up href attributes on the culture links.
More importantly though and related to my Documentation issue, it would be nicer if this could generate itself from a global list of supported cultures.

Javascript,
https://github.com/Code52/aspnet-internationalization/blob/master/src/Code52.i18n.MVC/NuSpec/Content/Scripts/Code52.i18n.js#L51

should that line be this.instance = ...

As I said in the chat room, I will try get some time to PR some of this stuff, at work atm and just brain dumping an issue list I put together while working with the library today.

**Comment by shiftkey** [comment]
> Firstly, .ascx? Ew :)

Done for compatibility and because (as you mention) both ViewEngines are loaded in MVC3 and up.

**Comment by shiftkey** [comment]
I've accepted #13 so if there's anything you'd like to add or remove feel free to kick off a different discussion on it.
