### ISSUE TITLE
LanguageSelection Partial - Build Action set incorrectly

### ISSUE THREAD

**Issue by csainty** [Code52/aspnet-internationalization#12]
Was added to my project with Build Action set to None, instead of Content.

I have seen similar things in other projects and think it might be a NuGet thing. In that case a step on the README file will be needed.

**Comment by shiftkey** [comment]
Are you seeing this happen consistently? 

I tried it with a few projects just now and am still seeing it set to Content (as expected).

What other details can you provide to help me nail it down?

**Comment by csainty** [comment]
Just tried a new project and it went in correctly as Content.

Not sure how to reproduce.

**Comment by shiftkey** [comment]
Feel free to reopen if you can spot the cause
