### ISSUE TITLE
CompareAttribute in Models is an ambiguous reference.

### ISSUE THREAD

**Issue by ignaciofuentes** [Code52/aspnet-internationalization#14]
The Compare Attribute that the ConfirmPassword property has (in both ChangePasswordModel and RegisterModel) fires a compile error:

'CompareAttribute' is an ambiguous reference between 'System.ComponentModel.DataAnnotations.CompareAttribute' and 'System.Web.Mvc.CompareAttribute'

This happens when running VS 11 with mvc Beta 4 and .Net 4.5.
Changing it .Net 4.0 "fixes it"

**Comment by shiftkey** [comment]
Apologies for missing this one. Now that MVC4 and .NET 4.5 are finalised I'll confirm this is not occurring.

**Comment by JakeGinnivan** [comment]
Still an issue in samples

**Comment by shiftkey** [comment]
To make this work between .NET4 and .NET45 you need to change your two using statements in those files to:

```
using System.ComponentModel.DataAnnotations;
using CompareAttribute = System.Web.Mvc.CompareAttribute;
```

Just pushed 0.2.6 to NuGet which fixes this specific issue but I've got more things I need to resolve still
