### ISSUE TITLE
Psuedoizer CmdLet Crashing VS

### ISSUE THREAD

**Issue by csainty** [Code52/aspnet-internationalization#9]
Looks like if it can not find the input file it simply crashes VS.

Quick look at the code shows the input file is being opened before the try / catch.

https://github.com/Code52/aspnet-internationalization/blob/master/src/Code52.i18n.Tools/Psuedoizer.cs#L21

Sorry I don't have time to make this a PR, but haven't worked with CmdLet's so no idea how to compile, install or test any fix I might make, or if there is a better way to output the error.

I couldn't work out what path context it runs in either. So I needed to use an absolute path in the end. This could be better documented?

**Comment by shiftkey** [comment]
Looks to be something more sinister - moving that first line inside the try-catch changed nothing. More digging necessary. ping @DavidChristiansen.

**Comment by shiftkey** [comment]
A bit more debugging confirms that relative paths break:

```
PM> Code52-Psuedoizer -InputResourceFile .\MvcApplication33\Resources\Language.resx -OutputResourceFile .\MvcApplication33\Resources\Language.pl.resx
Psuedoizer: Adapted from MSDN BugSlayer 2004-Apr i18n Article
 - generating resource file from .\MvcApplication33\Resources\Language.resx
 - output to .\MvcApplication33\Resources\Language.pl.resx
Input file C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\MvcApplication33\Resources\Language.resx could not be found, exiting...
Psuedoizer completed successfully
```

**Comment by shiftkey** [comment]
Closing this one off as relative path support (from the working directory of the powershell session) is now supported.

Will include in documentation.
